language: ruby
rvm:
  - 2.4.1
cache: bundler
sudo: false
services:
  - postgresql
  - redis-server
env:
  - DATABASE_URL_TEST=postgresql://localhost/caesar_test?user=postgres

before_script:
  - psql -c 'create database caesar_test;' -U postgres

script: "bin/rspec"
